/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package KUL.FluoSEMFX;

import mmcorej.CMMCore;
import java.text.NumberFormat;
import java.text.ParseException;
import java.util.prefs.Preferences;
import java.awt.event.ActionEvent; 
import java.awt.event.ActionListener; 
import javax.swing.Timer;
import org.micromanager.api.MMPlugin;
import org.micromanager.api.ScriptInterface;

/**
 *
 * @author supervisor
 */
public class FluoSEMFXLaserControlFrame extends javax.swing.JFrame {
    
    private final ScriptInterface m_gui;
    private final CMMCore m_core;

    /**
     * Creates new form FluoSEMFXLaserControl
     */
    public FluoSEMFXLaserControlFrame(ScriptInterface gui) {
        m_gui = gui;
        m_core = m_gui.getMMCore();

        initComponents();
        setLocation(0, 0);

        setBackground(m_gui.getBackgroundColor());
        m_gui.addMMBackgroundListener(this);
        
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
